# Directions
NORTH = 0
EAST  = 1
SOUTH = 2
WEST  = 3

# Tiles
TILE_NONE 	= 0
TILE_UP 	= 1
TILE_DOWN 	= 2
TILE_LEFT 	= 3
TILE_RIGHT	= 4

# Edges
DISCONNECTED = 0
CONNECTED 	 = 1

# Edges of tiles [North, East, South, West]
TileRules = {
	TILE_NONE: 	[DISCONNECTED, DISCONNECTED, DISCONNECTED, DISCONNECTED],
	TILE_UP: 	[CONNECTED, CONNECTED, DISCONNECTED, CONNECTED],
	TILE_DOWN: 	[DISCONNECTED, CONNECTED, CONNECTED, CONNECTED],
	TILE_LEFT: 	[CONNECTED, DISCONNECTED, CONNECTED, CONNECTED],
	TILE_RIGHT: [CONNECTED, CONNECTED, CONNECTED, DISCONNECTED],
}

TileImagePaths = [
	'None.png',
	'Up.png',
	'Down.png',
	'Left.png',
	'Right.png',
]